CREATE DATABASE QUANLYSUATAN_1;
 
USE QUANLYSUATAN_1;
 
CREATE TABLE TINH_THANH (
MA_TINH_THANH INT NOT NULL PRIMARY KEY,
TEN_TINH_THANH NVARCHAR(1000),
MO_TA_TINH_THANH NVARCHAR(4000),
MA_TINH_THANH_CHUAN VARCHAR(20),
MA_QUOC_GIA VARCHAR(20)
);
CREATE TABLE QUAN_HUYEN (
MA_QUAN_HUYEN VARCHAR(90) NOT NULL PRIMARY KEY,
MA_TINH_THANH INT,
TEN_QUAN_HUYEN NVARCHAR(1000),
MO_TA_QUAN_HUYEN NVARCHAR(4000),
MA_HUYEN_THEO_BHYT VARCHAR(100),
MA_QUAN_HUYEN_CHUAN VARCHAR(20),
FOREIGN KEY(MA_TINH_THANH) REFERENCES TINH_THANH(MA_TINH_THANH)
);
CREATE TABLE DON_VI (
MA_DON_VI VARCHAR(100) NOT NULL PRIMARY KEY,
TEN_DON_VI NVARCHAR(1000),
CAP_DON_VI INT,
MA_DON_VI_QUAN_LY VARCHAR(90),
MA_DON_VI_THAM_CHIEU VARCHAR(90),
THUOC_CAP_HUYEN INT,
MA_HUYEN VARCHAR(90),
QUAN_LY_HUYEN INT,
PKDK_THUOC_HUYEN INT,
DIA_CHI NVARCHAR(1000),
KY_HIEU_DON_VI VARCHAR(100),
TRANG_THAI INT,
MA_TINH INT,
SO_DIEN_THOAI VARCHAR(50),
EMAIL VARCHAR(50),
FAX VARCHAR(50),
HOT_LINE VARCHAR(50),
MO_TA VARCHAR(1000),
SO_GIUONG VARCHAR(255),
FOREIGN KEY(MA_HUYEN) REFERENCES QUAN_HUYEN(MA_QUAN_HUYEN),
FOREIGN KEY(MA_TINH) REFERENCES TINH_THANH(MA_TINH_THANH)
);
CREATE TABLE KHOA(
MA_KHOA INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
TEN_KHOA NVARCHAR(100),
MA_DON_VI VARCHAR(100),
CAP_KHOA_PHONG INT,
KY_HIEU_KHOA_PHONG VARCHAR(100),
SO_DIEN_THOAI VARCHAR(15),
FOREIGN KEY(MA_DON_VI) REFERENCES DON_VI(MA_DON_VI)
);
CREATE TABLE BENH_NHAN(
MA_BENH_NHAN INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
TEN_BENH_NHAN NVARCHAR(40),
GIOI_TINH NVARCHAR(3),
NGAY_SINH DATETIME,
DIA_CHI NVARCHAR(100),
BHYT TINYINT,
GIUONG INT,
CHUAN_DOAN NVARCHAR(100),
DU_DOAN_SO_NGAY_DIEU_TRI INT,
MA_KHOA INT,
FOREIGN KEY(MA_KHOA) REFERENCES KHOA(MA_KHOA));

CREATE TABLE NHA_HAO_TAM(
MA_NHT INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
TEN_NHT NVARCHAR(40));

CREATE TABLE CHI_TIET_TAI_TRO(
MA_NHT INT,
NGAY_TAI_TRO DATETIME,
SO_LUONG_TAI_TRO INT,
PRIMARY KEY(MA_NHT, NGAY_TAI_TRO),
FOREIGN KEY(MA_NHT) REFERENCES NHA_HAO_TAM(MA_NHT));

CREATE TABLE CAN_BO_MANG_LUOI(
MA_CAN_BO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
TEN_CAN_BO NVARCHAR(100),
GIOI_TINH NVARCHAR(3),
NGAY_SINH DATETIME,
KHOA INT,
FOREIGN KEY(KHOA) REFERENCES KHOA(MA_KHOA));

CREATE TABLE DON_DE_XUAT(
MA_DON INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
MA_BENH_NHAN INT,
LI_DO NVARCHAR(100),
CHE_DO_AN TINYINT,
SO_PHIEU_LAN_1 INT,
SO_PHIEU_LAN_2 INT,
SO_PHIEU_LAN_3 INT,
TINH_TRANG_DUYET TINYINT,
NGAY_LAP VARCHAR(15),
NGAY_DUYET VARCHAR(15),
FOREIGN KEY(MA_BENH_NHAN) REFERENCES BENH_NHAN(MA_BENH_NHAN));

CREATE TABLE PHIEU_AN(
MA_PHIEU_AN INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
NGAY_TAO DATETIME,
TINH_TRANG TINYINT,
NGUOI_IN INT,
FOREIGN KEY(NGUOI_IN) REFERENCES CAN_BO_MANG_LUOI(MA_CAN_BO));

CREATE TABLE CHI_TIET_PHIEU_AN(
MA_PHIEU_AN INT,
MA_BENH_NHAN INT,
NGAY_PHAT_PHIEU DATETIME,
NGAY_SU_DUNG DATETIME,
PRIMARY KEY(MA_BENH_NHAN, MA_PHIEU_AN),
FOREIGN KEY(MA_PHIEU_AN) REFERENCES PHIEU_AN(MA_PHIEU_AN),
FOREIGN KEY(MA_BENH_NHAN) REFERENCES BENH_NHAN(MA_BENH_NHAN));

-- -----------------------------------------------INSERT VALUE--------------------------------
INSERT INTO BENH_NHAN(TEN_BENH_NHAN) VALUES('Bệnh nhân 01');
INSERT INTO BENH_NHAN(TEN_BENH_NHAN) VALUES('Bệnh nhân 02');
INSERT INTO BENH_NHAN(TEN_BENH_NHAN) VALUES('Bệnh nhân 03');
INSERT INTO BENH_NHAN(TEN_BENH_NHAN) VALUES('Bệnh nhân 04');
-- SELECT * FROM BENH_NHAN;

INSERT INTO DON_DE_XUAT(MA_BENH_NHAN, LI_DO, CHE_DO_AN, SO_PHIEU_LAN_1, SO_PHIEU_LAN_2, SO_PHIEU_LAN_3, TINH_TRANG_DUYET, NGAY_LAP, NGAY_DUYET) VALUES(1,'Đơn đề xuất của bệnh nhân 01', 1, 10, 0, 0, 0, '21/03/2019', '21/03/2019');
INSERT INTO DON_DE_XUAT(MA_BENH_NHAN, LI_DO, CHE_DO_AN, SO_PHIEU_LAN_1, SO_PHIEU_LAN_2, SO_PHIEU_LAN_3, TINH_TRANG_DUYET, NGAY_LAP, NGAY_DUYET) VALUES(2,'Đơn đề xuất của bệnh nhân 02', 1, 15, 0, 0, 0, '21/03/2019', '21/03/2019');
INSERT INTO DON_DE_XUAT(MA_BENH_NHAN, LI_DO, CHE_DO_AN, SO_PHIEU_LAN_1, SO_PHIEU_LAN_2, SO_PHIEU_LAN_3, TINH_TRANG_DUYET, NGAY_LAP, NGAY_DUYET) VALUES(3,'Đơn đề xuất của bệnh nhân 03', 1, 20, 0, 0, 0, '21/03/2019', '21/03/2019');
INSERT INTO DON_DE_XUAT(MA_BENH_NHAN, LI_DO, CHE_DO_AN, SO_PHIEU_LAN_1, SO_PHIEU_LAN_2, SO_PHIEU_LAN_3, TINH_TRANG_DUYET, NGAY_LAP, NGAY_DUYET) VALUES(4,'Đơn đề xuất của bệnh nhân 04', 1, 35, 0, 0, 0, '21/03/2019', '21/03/2019');
-- delete from DON_DE_XUAT where ma_don in(select ma_don from don_de_xuat);
-- delete from DON_DE_XUAT where ma_don = 7;
-- ------------------------------------------------DON_DE_SUAT-------------------------------------
-- -DANH SACH DON DE SUAT:
DELIMITER //
CREATE  PROCEDURE DanhSachDonDeXuat()
BEGIN
	SELECT * FROM DON_DE_XUAT; 
END
//
DELIMITER ;
-- CALL DANH_SACH_DON_DE_SUAT();

DELIMITER //
CREATE PROCEDURE LayDonDeXuatTuMaDon(_ma_don int unsigned)
BEGIN
	SELECT * FROM DON_DE_XUAT WHERE MA_DON = _ma_don; 
END
//
DELIMITER ;

DELIMITER //
CREATE PROCEDURE ThemDonDeXuat(_ma_benh_nhan int unsigned, _li_do nvarchar(100), _che_do_an int, _so_phieu_lan_1 int,  _so_phieu_lan_2 int, _so_phieu_lan_3 int, _tinh_trang int, _ngay_lap varchar(15), _ngay_duyet varchar(15))
BEGIN
	INSERT INTO DON_DE_XUAT(MA_BENH_NHAN, LI_DO, CHE_DO_AN, SO_PHIEU_LAN_1, SO_PHIEU_LAN_2, SO_PHIEU_LAN_3, TINH_TRANG_DUYET, NGAY_LAP, NGAY_DUYET) VALUES(_ma_benh_nhan, _li_do, _che_do_an, _so_phieu_lan_1, _so_phieu_lan_2, _so_phieu_lan_3, _tinh_trang, _ngay_lap, _ngay_duyet);
	COMMIT;
END
//
DELIMITER ;

DELIMITER //
CREATE PROCEDURE CapNhatDonDeXuat(_ma_don int unsigned, _ma_benh_nhan int unsigned, _li_do nvarchar(100), _che_do_an int, _so_phieu_lan_1 int,  _so_phieu_lan_2 int, _so_phieu_lan_3 int, _tinh_trang int, _ngay_lap varchar(15), _ngay_duyet varchar(15))
BEGIN
	UPDATE DON_DE_XUAT SET MA_BENH_NHAN = _ma_benh_nhan, LI_DO = _li_do, CHE_DO_AN =_che_do_an, SO_PHIEU_LAN_1 = _so_phieu_lan_1, SO_PHIEU_LAN_2 = _so_phieu_lan_2, SO_PHIEU_LAN_3 = _so_phieu_lan_3, TINH_TRANG_DUYET =_tinh_trang, NGAY_LAP =_ngay_lap, NGAY_DUYET = _ngay_duyet WHERE MA_DON = _ma_don;
	COMMIT;
END
//
DELIMITER ;

DELIMITER //
CREATE PROCEDURE XoaDonDeXuat(_ma_don int unsigned)
BEGIN
	DELETE FROM DON_DE_XUAT WHERE MA_DON = _ma_don;
    COMMIT;
END
//
DELIMITER ;

-- ---------------------------------------------------KHOA--------------------------------------------------
-- DANH SACH KHOA:
DELIMITER //
CREATE PROCEDURE DANH_SACH_KHOA()
BEGIN
	SELECT * FROM KHOA; 
END;
DELIMITER ;
-- EXEC DANH_SACH_KHOA

-- --------------------------------------------------BENH_NHAN---------------------------------------------
-- DANH SACH BENH_NHAN:

DELIMITER //
CREATE PROCEDURE DANH_SACH_BENH_NHAN()
BEGIN
	SELECT * FROM BENH_NHAN; 
END;
DELIMITER ;

-- EXEC DANH_SACH_BENH_NHAN
-- -------------------------------------------------NHA_HAO_TAM----------------------------------------------
-- DANH SACH NHA_HAO_TAM:
 
DELIMITER //

CREATE PROCEDURE DANH_SACH_NHA_HAO_TAM()
BEGIN
	SELECT * FROM NHA_HAO_TAM; 
END;
//

DELIMITER ;


-- EXEC DANH_SACH_NHA_HAO_TAM
-- -------------------------------------------------NHA_HAO_TAM + CHI_TIEC-----------------------------------
-- DANH SACH NHA_HAO_TAM + TAI_TRO
 
DELIMITER //

CREATE PROCEDURE DANH_SACH_NHA_HAO_TAM_CHI_TIET()
BEGIN
	SELECT * FROM NHA_HAO_TAM,CHI_TIET_TAI_TRO WHERE NHA_HAO_TAM.MA_NHT=CHI_TIET_TAI_TRO.MA_NHT; 
END;
//

DELIMITER ;


-- EXEC DANH_SACH_NHA_HAO_TAM_CHI_TIET
-- GO 
-- -----------------------------------------------CAN_BO_MANG_LUOI-----------------------------------------------
-- DANH SACH CAN_BO_MANG_LUOI:
 
DELIMITER //

CREATE PROCEDURE DANH_SACH_CAN_BO_MANG_LUOI()
BEGIN
	SELECT * FROM CAN_BO_MANG_LUOI;
END;
-- GO
-- EXEC DANH_SACH_CAN_BO_MANG_LUOI
-- ----------------------------------------------PHIEU AN VA CHI TIEC --------------------------------
-- DANH SACH PHIEU_AN VA CHI TIET
//

DELIMITER ;


DELIMITER //

CREATE PROCEDURE DANH_SACH_PHIEU_AN_CHI_TIET()
BEGIN
	SELECT * FROM PHIEU_AN AS PA,CHI_TIET_PHIEU_AN AS CTPA WHERE PA.MA_PHIEU_AN =CTPA.MA_PHIEU_AN;
END;
//

DELIMITER ;


-- EXEC DANH_SACH_PHIEU_AN_CHI_TIET
-- GO
